### ISSUE TITLE
Cargo.toml is misconfigured

### ISSUE THREAD

**Issue by dakthompson** [Abdiramen/Fractalinator#1]
When attempting to build the project using Cargo I am confronted with the error: `couldn't read src/lib.rs: The system cannot find the file specified. (os error 2)`

**Comment by Abdiramen** [comment]
thanks for the heads up it's fixed in this commit https://github.com/Abdiramen/Fractalinator/commit/616c66c188806007d2d4a43affd8ad99e560a8a3
